@hostname = localhost
@port = 3000

### PRODUCTS
@productId = 60e7766b10a3216f4f942c47

### CREATE
POST http://{{hostname}}:{{port}}/products
Content-Type: application/json

{
  "name": "Produto 1",
  "quantity": 10
}

### GET ALL
GET http://{{hostname}}:{{port}}/products

### FIND BY ID
GET http://{{hostname}}:{{port}}/products/{{productId}}

### UPDATE BY ID
PUT http://{{hostname}}:{{port}}/products/{{productId}}
Content-Type: application/json

{
  "name": "Produto 1",
  "quantity": 18
}

### DELETE BY ID
DELETE http://{{hostname}}:{{port}}/products/{{productId}}

### SALES
@saleId = 60e776dd0e997a6fb917ad00

### CREATE
POST http://{{hostname}}:{{port}}/sales
Content-Type: application/json

[
  {
    "productId": "60e7766b10a3216f4f942c47",
    "quantity": 15
  }
]

### GET ALL
GET http://{{hostname}}:{{port}}/sales

### FIND BY ID
GET http://{{hostname}}:{{port}}/sales/{{saleId}}

### UPDATE BY ID
PUT http://{{hostname}}:{{port}}/sales/{{saleId}}
Content-Type: application/json

[
  {
    "productId": "60e7766b10a3216f4f942c47",
    "quantity": 25
  }
]

### DELETE BY ID
DELETE http://{{hostname}}:{{port}}/sales/{{saleId}}
